# -*- coding: utf-8 -*-
"""Extract_text_from_image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yoj8IDR8OHvz67YUMJl_Pwtuz3Ouu_kL

**0.import libraries**
"""

import easyocr 
import cv2
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

"""**1.Read in aimages or video**"""

IMAGE_PATH = 'sign1.PNG'

reader = easyocr.Reader(['en'], gpu=True)
result = reader.readtext(IMAGE_PATH)
result

result.save

result[0]

result[1]

"""**2.Draw Results** """

top_left = tuple(result[0][0][0])
bottom_right = tuple(result[0][0][2])
text = result[0][1]
font = cv2.FONT_HERSHEY_SIMPLEX

img = cv2.imread(IMAGE_PATH)
img = cv2.rectangle(img, top_left, bottom_right, (0,255,0), 5)
img = cv2.putText(img, text, top_left, font, .5, (255, 255, 255), 2, cv2.LINE_AA)
plt.imshow(img)
plt.show()

"""**3.Handling Multiple Lines**"""

img = cv2.imread(IMAGE_PATH)
for detection in result:
  top_left = tuple([int(val) for val in detection[0][0]])
  bottom_right = tuple([int(val) for val in detection[0][2]])
  text = detection[1]
  font = cv2.FONT_HERSHEY_SIMPLEX
  img = cv2.rectangle(img, top_left, bottom_right, (0,255,0), 5)
  img = cv2.putText(img, text, top_left, font, 3, (255,255,255),3, cv2.LINE_AA)

plt.figure(figsize=[10,10])
plt.imshow(img)
plt.show()